### ISSUE TITLE
Rename OOC tab into Out of Character / Game

### ISSUE THREAD

**Issue by apoapostolov** [cswendrowski/FoundryVTT-Tabbed-Chatlog#1]
It really triggers OCD when out of all labels, only the last one uses an abbreviation. It can be "Out of Game" label if "Out of Character" cannot be fit in at all (even with slightly wider tab).

**Comment by MrBrentRogers** [comment]
Or just have "Out of Character" on mouse over.

**Comment by cswendrowski** [comment]
I made it "OOC" for space reasons - otherwise, it renders like this; 
![image](https://user-images.githubusercontent.com/15639841/87859558-9d528980-c8fb-11ea-9858-d73fefd000e5.png)

I didn't want to expand the width of the sidebar just for this module, but I'm open to suggestions!

**Comment by apoapostolov** [comment]
Thanks for the reply. Out of Game was my alternative suggestion exactly because I expected spill in English (worse in German, etc.)
