### ISSUE TITLE
Optional Setup - In Game / Out of Game

### ISSUE THREAD

**Issue by apoapostolov** [cswendrowski/FoundryVTT-Tabbed-Chatlog#10]
While I like the current 3-tab setup of the mod, two groups of players I DM to both find it annoying as they have to switch often between In Character and Rolls. 

Both groups suggested their preferred method is 2-tab setup with In Game (both in-game messages and roll messages) and Out of Game (the spam, the memes, etc.). Please consider adding a Settings option to support a 2-tab mode as optional.

**Comment by cswendrowski** [comment]
I've determined that I will never be able to do this work without rewriting the module from scratch. Unfortunately, 3 tabs is all it will be - no more, no less
