### ISSUE TITLE
Theatre Inserts compatibility?

### ISSUE THREAD

**Issue by nearlyNonexistent** [cswendrowski/FoundryVTT-Tabbed-Chatlog#12]
I know the module Theatre Inserts is no longer being updated, but would it be too much of a hassle to ask for compatibility? What happens is that messages sent with it don't count as "IC" according to the chat tab. It might help to add some kind of fallback to "make" it count maybe?

**Comment by cswendrowski** [comment]
Unfortunately Theater itself would need to make that change. You might be interested in a new project of mine, which is fully compatible with Tabbed Chat: https://www.youtube.com/watch?v=6A8ORdQG_RA
