### ISSUE TITLE
1.3.6 - clicking on a token repositions the map view 

### ISSUE THREAD

**Issue by RicoTheBold** [cswendrowski/FoundryVTT-Tabbed-Chatlog#15]
As of 1.3.6, when I click on a token on a map (as the GM), the entire map view resets to center the map and zoom out enough that the whole map is in view.  This is _super_ annoying.  It didn't do it with 1.3.5 (I think it was 1.3.5 - that version seemed to incorrectly report its version number in the updater and always thought it needed to update).

I downloaded the zip for 1.3.5 and used the _tabbed-chatlog.js_ from it to replace the one in 1.3.6 and the behavior went away.

I'm guessing this is the offending line in 1.3.6, which I found by comparing the two files:

`  canvas.pan({ x: canvas.dimensions.width / 2, y: canvas.dimensions.height / 2, scale: 1 - (canvas.dimensions.sceneHeight / canvas.dimensions.height) });
`
I didn't try to go through all the code to figure out _why_ this is being done, but wow, it's annoying.

**Comment by cswendrowski** [comment]
This is fixed, I apologize for introducing a feature from a different module I was working on (Streaming Mode)
