### ISSUE TITLE
Rolls From Characters in Different Scenes are Not Separated

### ISSUE THREAD

**Issue by nflutz** [cswendrowski/FoundryVTT-Tabbed-Chatlog#17]
When two players have characters dragged to different scenes, a dice-roll from one character is seen by characters that are currently in a different scene. Per the GIF in the github README it looks like only players in the current scene should only see a dice-roll in the dice-roll tab if the roll was made by a character in the same scene, similar to the behavior of the In Character tab.
![Capture](https://user-images.githubusercontent.com/1378050/93923588-35446900-fcd9-11ea-8314-d96aeba10823.JPG)

**Comment by cswendrowski** [comment]
This should now be resolved
