### ISSUE TITLE
Allow Gamemaster to Type IC Without Character

### ISSUE THREAD

**Issue by Ranimara** [cswendrowski/FoundryVTT-Tabbed-Chatlog#19]
I'm so happy I found this module.  The one thing that's missing is the lack of an easy way for the Gamemaster to type IC.  I do most of my narrative text just typing as the Gamemaster and do not select a character.  This leads to all of my narrative ending up in the OOC tab.  It would be nice to have a way for the Gamemaster to type IC without having to select a character.

**Comment by anathemamask** [comment]
My current method for handling this in my own games is to create an actor called "Narrator" and assign that as my selected character for GM by rightclicking my own username and choosing Narrator from the 'select character' list.

**Comment by cswendrowski** [comment]
Foundry does not provide a way, to the best of my knowledge, offer a way to generically speak in-character without an Actor to be the speaker. I recommend following @anathemamask's workflow
