### ISSUE TITLE
Inline Rolls In Rolls Tab

### ISSUE THREAD

**Issue by haksanlulz** [cswendrowski/FoundryVTT-Tabbed-Chatlog#24]
I have some players in some of my games who prefer inline rolls just for one reason or another.  I would appreciate it if, as an option, you could make it so anything with inline rolls showed up in the rolls section as well. Perhaps even as a per-client setting rather than table wide.

**Comment by avion540** [comment]
I would appreciate this as well. As a player, I enjoy creating macros that include inline rolls. At the moment these get sent to OOC, but it would great if they could show up in the rolls tab instead.

**Comment by cswendrowski** [comment]
Hey there! Sorry for the delay. @avion540 if you could share a macro that you use, that'd make looking into this easier

**Comment by cswendrowski** [comment]
Although Foundry natively creates Inline rolls as type Other, you can use a macro to do so like so:

```js
ChatMessage.create({"content": "[[d20]]", "type": "5"})
```
