### ISSUE TITLE
Request: Show player's avatar in OOC

### ISSUE THREAD

**Issue by winterwulf** [cswendrowski/FoundryVTT-Tabbed-Chatlog#27]
It is silly and might not be worth the time to implement but I think would be a nice touch.
by player avatar I mean this (https://i.imgur.com/lV8tv83.png)

**Comment by winterwulf** [comment]
What I am saying is show the player avatar in discord linked channel.

**Comment by cswendrowski** [comment]
I'll see if I can easily add this

**Comment by cswendrowski** [comment]
I'm honestly not sure when I added this, but if an avatar is set, OOC should correctly grab it for Discord
