### ISSUE TITLE
[Bug] Chat card replacement not working

### ISSUE THREAD

**Issue by weihanderz** [cswendrowski/FoundryVTT-Tabbed-Chatlog#28]
Any mod that replaces chat card (ie better rolls 5e, etc) will look like the card will be deleted completely until the user switches to anther chat tab and back again.

**Comment by cswendrowski** [comment]
I'm not sure that's anything I can fix, but I'll take a peek

**Comment by cswendrowski** [comment]
I was unable to find a fix, it's likely they'll need to add compat on their side
