### ISSUE TITLE
Make a changelog

### ISSUE THREAD

**Issue by tmcclintock** [cswendrowski/FoundryVTT-Tabbed-Chatlog#29]
Right now the version updates are in the README, and the highest version described in the README is behind the most recent version on foundry (1.3.4 vs 1.5.7). I am requesting that a CHANGELOG be created with this information located in that file, and hopefully it gets updated with each minor release :).

**Comment by cswendrowski** [comment]
I'll update the changelog in the README then copy it to a new file, thanks for the request
