### ISSUE TITLE
Improve positioning of new posts notification badge

### ISSUE THREAD

**Issue by apoapostolov** [cswendrowski/FoundryVTT-Tabbed-Chatlog#3]
When a Tabbed chat gets new posts the (!) notification badge should be next to the tab title since the tabs do not have a border drawn if not selected. This makes the notification badge appear as if it belong to another tab, especially for users who are not used to the positioning and the invisible tabs. 

![image](https://user-images.githubusercontent.com/4083812/87242062-f5881800-c431-11ea-814d-2e7ad8d46312.png)

**Comment by cswendrowski** [comment]
Fixed in v1.5.0
