### ISSUE TITLE
[Request] Create role/player callouts in output for Discord webhooks

### ISSUE THREAD

**Issue by LonePaladin** [cswendrowski/FoundryVTT-Tabbed-Chatlog#37]
This module gives the option to attach a webhook to a game, or to individual scenes, that cause the IC or OOC/Rolls tabs to send their output to a selected Discord channel. It would be helpful to include an option to attach the code needed to make this output notify specific users for that channel. It could be keyed so that certain events (such as initiative during combat) create this callout for the owners of relevant actors.

The format is `<#ChannelID> <@UserID> <&RoleID>`.

For instance, one of my users' IDs is 201769097703325696. So when an actor that player owns comes up in the initiative list, it would include this text: <@201769097703325696> In the output to Discord, it would replace that text with the user's ID, causing Discord to notify that player.

It would need to add an option to each player (probably in the Player Configuration window) to input their ID numbers, then it would look for any activity involving actors they own, and add that text somewhere in it. It could optionally have a field where you enter the Channel ID so that it outputs to a different channel, or the Role ID so that it instead notifies everyone with the chosen role.

**Comment by LonePaladin** [comment]
A clarification: with the way this module creates the text for a Discord webhook, it already has the ability to create a ping in Discord. To use the example number I posted, I could just go into the OOC Chat tab, enter:

> `<@201769097703325696> test`

And in the Discord channel, it would output

> `@ThatUser test`

And that user would receive a notification. The webhook parses the number into that user's ID.

**Comment by cswendrowski** [comment]
I am using the Turndown library to be able to convert HTML styles into Markdown such that Discord may render it correctly. The library unfortunately sees the `<@user#123>` format as HTML and gets rid of it. I've tried a few workarounds, but no dice.

Sending the id does seem to work, but that's a UX that seems too unintuitive for most users, and isn't what I really am aiming for Tabbed Chat to do.

I recommend you use https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib and https://foundryvtt.com/packages/launchmacro/ to setup a hook macro on `preCreateChatMessage`, then swap any mentions of `@ThatUser` with your discord id
