### ISSUE TITLE
PF2 Spells, Feats posted to OOC first, but then not present in OOC but in Rolls

### ISSUE THREAD

**Issue by apoapostolov** [cswendrowski/FoundryVTT-Tabbed-Chatlog#4]
Seems like a bug. Posted spells, feats, etc. should go to Rolls as these posts are not player chat neither character talk. They are properly filtered there but they are not immediately sent there upon trigger and instead are sent to OOC.

**Comment by cswendrowski** [comment]
@apoapostolov is this happening in v1.0.2?

**Comment by apoapostolov** [comment]
Works as intended in 1.1.2.
