### ISSUE TITLE
Private rolls shows when changing and returning to rolls tab

### ISSUE THREAD

**Issue by owen-tenerife32** [cswendrowski/FoundryVTT-Tabbed-Chatlog#43]
I installed Actually Private Rolls module to my foundry to hide my rolls and do not notify my players that I made a roll on my end. At first it works perfectly fine when I go the the rolls tab of the tabbed chatlog module but when I change tab and return back, the gmroll card/text was displayed.
This bug also shows if Midi-QoL is also installed for the hide gm roll functionality

**Comment by Talaren** [comment]
Actually Private Rolls is very old, and foundry itself can hide this rolls i think this issue can closed

**Comment by owen-tenerife32** [comment]
Even if I use Foundry's dedicated private roll, it still occurs

**Comment by Talaren** [comment]
@owen-tenerife32 
Unfortunately, I can not reconstruct the behavior.
I have tested it with both FATE Core and DSA5.
I suspect the error depends on the ruleset used.
What ruleset are you using?
