### ISSUE TITLE
Tabbed chatlog doesn't seem to update or work correctly on /stream page

### ISSUE THREAD

**Issue by hakimassouane** [cswendrowski/FoundryVTT-Tabbed-Chatlog#46]
Hello,

I wanted to use the stream page to be able to stream the chat on OBS but I encountered a problem : The tabbed chatlog seems to  not update correctly on the /stream page

When I roll with any actor on the "Rolls tab" of the /game foundry page I see my roll, but when i switch to the /stream page the roll doesn't exist here (even though I'm also on the "Rolls tab" on the /stream page). When I switch tabs on the /stream page for example let's say Rolls tab -> OOC -> Rolls tab my roll is now showing here

Do you have any Idea why ? I attached two screenshots of the problem

[Screen 1](https://ibb.co/SBPSRM7)
[Screen 2](https://ibb.co/R0TbQT9)

**Comment by Talaren** [comment]
@hakimassouane the main problem is on stream page is "game.user.viewedScene" is null so he think he must hide alle entrys without the ooc this is a global chat, not bounded to a scene.
i search for the information on the data but nothing found, the variable szene is on the stream page null :(

**Comment by cswendrowski** [comment]
At some point I added detection for /stream such that Tabbed Chat doesn't try to tab nor filter on that page
