### ISSUE TITLE
Discord webhooks

### ISSUE THREAD

**Issue by Olberycht** [cswendrowski/FoundryVTT-Tabbed-Chatlog#47]
Hello,

I tried to use webhooks to send incharacter et ooc chat to my Discord server but it seems to not working. I tried with an another module (DiscordConnect) and, with a delay, messages pop up.

I don't know what's the problem and it's not critical but if it can be solved.

Thank you :)

**Comment by Talaren** [comment]
@Olberycht had the same problem and write a fix tested with my fork.
https://raw.githubusercontent.com/Talaren/FoundryVTT-Tabbed-Chatlog/master/module.json

**Comment by Olberycht** [comment]
> @Olberycht had the same problem and write a fix tested with my fork.
> https://raw.githubusercontent.com/Talaren/FoundryVTT-Tabbed-Chatlog/master/module.json

Very much thank you ! It work perfectly.
