### ISSUE TITLE
Bug : 0.8.6 'automatic OOC chat when OOC tab is active' option doesn't work

### ISSUE THREAD

**Issue by jbblily** [cswendrowski/FoundryVTT-Tabbed-Chatlog#48]
I have updated to 0.8.6 stable.
I checked the option, but it doesn't work. 
It still goes into In character tab.

**Comment by Talaren** [comment]
@jbblily Foundry refactoring the data structure. 
tested my fix in my repo
https://raw.githubusercontent.com/Talaren/FoundryVTT-Tabbed-Chatlog/master/module.json

**Comment by jbblily** [comment]
Hmm, you have already closed this but it still doesn't work.
I checked the option 'When in OOC tab, should In Character chat be converted to OOC?' 
In character chat (activated occ tab) still goes into In Character tab. 
And I completely used no modules other than Tabbed Chatlog.

**Comment by jbblily** [comment]
Hmm, thanks but it seems still not working on me
No modules, only tabbed chatlog, activated 'in character chat at ooc tab converted into ooc chat'.
It is still counted as ic chat... 
but thank you for the update!

**Comment by Talaren** [comment]
@jbblily have pushed an update, can you test it?

**Comment by jbblily** [comment]
@Talaren I tested your fix, and it worked! Thanks a lot. Waiting for the update!
