### ISSUE TITLE
Provide pop-out support for tabs

### ISSUE THREAD

**Issue by anathemamask** [cswendrowski/FoundryVTT-Tabbed-Chatlog#5]
The only feature missing! 

Add right-click support to pop the tab out into a new Application. Bonus points if it has a configurable option to pop into a window all its own.

**Comment by cswendrowski** [comment]
I have no idea how to do this at the moment, but I'll take a look!

**Comment by cswendrowski** [comment]
Salon, written by @anathemamask, provides this feature. I have no plans to add it myself at this point
