### ISSUE TITLE
Scroll to bottom when switching tabs

### ISSUE THREAD

**Issue by tscs37** [cswendrowski/FoundryVTT-Tabbed-Chatlog#6]
When switching tabs in Foundry, the tab scrolls up to the oldest available message, not the newest message. Especially for rolls this causes some inconvenience when as a DM I have to scroll through the entire chat log before seeing the result.

**Comment by cswendrowski** [comment]
@tscs37 This should be fixed in the latest version!

**Comment by tscs37** [comment]
Fixed, thanks!
