### ISSUE TITLE
OOC bug

### ISSUE THREAD

**Issue by C4M3R0N808** [cswendrowski/FoundryVTT-Tabbed-Chatlog#60]
Hello, I just downloaded and was trying your module in 8.9 (despite compatibility saying 8.8).
It seems there is a bug with the OOC chat where it is unable to flush the chat log. The other tabs work fine, but the 3rd doesnt seem to work.

**Comment by superpcm** [comment]
Can confirm, can't flush chat logs, but I'm using 0.9.9.

**TypeError: this.object is undefined**

**Comment by cswendrowski** [comment]
Closed as of v1.6.4
