### ISSUE TITLE
Improve the click detection of the tabs

### ISSUE THREAD

**Issue by saif-ellafi** [cswendrowski/FoundryVTT-Tabbed-Chatlog#62]
Right now, it works fine if we click over the text of the tab, but clicking anywhere in between, takes us to the "In Character" tab. I guess it is not intended, it can cause a bit of frustration when missing "Rolls" by a pixel and ending up in the wrong tab.

**Comment by cswendrowski** [comment]
The target of the click is the entire tab item, in my testing of the latest I can click outside the text to get to the tab. Can you try again in v1.6.4 in V9 of Foundry?

**Comment by saif-ellafi** [comment]
Yes! All good in the latest build - Thanks!
