### ISSUE TITLE
Foundry v12 support

### ISSUE THREAD

**Issue by keneth-dev** [cswendrowski/FoundryVTT-Tabbed-Chatlog#78]
The module no longer works on v12. Are there any plans for updating it?

**Comment by Myriade91** [comment]
If you have some time, i'd like a v12 update too.

**Comment by solidsingularity** [comment]
Any update on v12?

**Comment by ryzimmer** [comment]
Reached out to repo owner. Looks like they no longer plan to support this

**Comment by keneth-dev** [comment]
That's unfortunate. I created my own bare-bones module for it back in August. It doesn't have all of the same features, but if anyone needs a v12-compliant one, you can find it at: https://github.com/keneth-dev/foundry-chat-tabs.
