### ISSUE TITLE
Error thrown if no active scene

### ISSUE THREAD

**Issue by anathemamask** [cswendrowski/FoundryVTT-Tabbed-Chatlog#9]
Rare cases where there is no active or selected scene result in 

TypeError: Cannot read property 'id' of undefined at tabbed-chatlog.js:162

**Comment by anathemamask** [comment]
Still getting thrown errors if no active scene; apparently breaks salon too. 

***woops***

**Comment by cswendrowski** [comment]
Should be resolved, let me know!
